//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.FEBata {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.online.asp.core.paperless.cl", ConfigurationName="FEBata.OnlinePortType")]
    public interface OnlinePortType {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecovery", ReplyAction="urn:OnlineRecoveryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.FEBata.OnlineRecoveryResponse OnlineRecovery(CapaPresentacion.FEBata.OnlineRecoveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecovery", ReplyAction="urn:OnlineRecoveryResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineRecoveryResponse> OnlineRecoveryAsync(CapaPresentacion.FEBata.OnlineRecoveryRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:CargaInformeBajas", ReplyAction="urn:CargaInformeBajasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.FEBata.CargaInformeBajasResponse CargaInformeBajas(CapaPresentacion.FEBata.CargaInformeBajasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CargaInformeBajas", ReplyAction="urn:CargaInformeBajasResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.CargaInformeBajasResponse> CargaInformeBajasAsync(CapaPresentacion.FEBata.CargaInformeBajasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineARC", ReplyAction="urn:OnlineARCResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.FEBata.OnlineARCResponse OnlineARC(CapaPresentacion.FEBata.OnlineARCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineARC", ReplyAction="urn:OnlineARCResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineARCResponse> OnlineARCAsync(CapaPresentacion.FEBata.OnlineARCRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineConsultaEstado", ReplyAction="urn:OnlineConsultaEstadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.FEBata.OnlineConsultaEstadoResponse OnlineConsultaEstado(CapaPresentacion.FEBata.OnlineConsultaEstadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineConsultaEstado", ReplyAction="urn:OnlineConsultaEstadoResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineConsultaEstadoResponse> OnlineConsultaEstadoAsync(CapaPresentacion.FEBata.OnlineConsultaEstadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:GenInformeReversiones", ReplyAction="urn:GenInformeReversionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.FEBata.GenInformeReversionesResponse GenInformeReversiones(CapaPresentacion.FEBata.GenInformeReversionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GenInformeReversiones", ReplyAction="urn:GenInformeReversionesResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.GenInformeReversionesResponse> GenInformeReversionesAsync(CapaPresentacion.FEBata.GenInformeReversionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:AddDocInfo", ReplyAction="urn:AddDocInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.FEBata.AddDocInfoResponse AddDocInfo(CapaPresentacion.FEBata.AddDocInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AddDocInfo", ReplyAction="urn:AddDocInfoResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.AddDocInfoResponse> AddDocInfoAsync(CapaPresentacion.FEBata.AddDocInfoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarAdjuntosRecibidos", ReplyAction="urn:listarAdjuntosRecibidosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.FEBata.listarAdjuntosRecibidosResponse listarAdjuntosRecibidos(CapaPresentacion.FEBata.listarAdjuntosRecibidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarAdjuntosRecibidos", ReplyAction="urn:listarAdjuntosRecibidosResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.listarAdjuntosRecibidosResponse> listarAdjuntosRecibidosAsync(CapaPresentacion.FEBata.listarAdjuntosRecibidosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRecList", ReplyAction="urn:OnlineRecoveryRecListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.FEBata.OnlineRecoveryRecListResponse OnlineRecoveryRecList(CapaPresentacion.FEBata.OnlineRecoveryRecListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRecList", ReplyAction="urn:OnlineRecoveryRecListResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineRecoveryRecListResponse> OnlineRecoveryRecListAsync(CapaPresentacion.FEBata.OnlineRecoveryRecListRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:InformeResBoletasDiario", ReplyAction="urn:InformeResBoletasDiarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.FEBata.InformeResBoletasDiarioResponse InformeResBoletasDiario(CapaPresentacion.FEBata.InformeResBoletasDiarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:InformeResBoletasDiario", ReplyAction="urn:InformeResBoletasDiarioResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.InformeResBoletasDiarioResponse> InformeResBoletasDiarioAsync(CapaPresentacion.FEBata.InformeResBoletasDiarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ConsultaInformeReversiones", ReplyAction="urn:ConsultaInformeReversionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.FEBata.ConsultaInformeReversionesResponse ConsultaInformeReversiones(CapaPresentacion.FEBata.ConsultaInformeReversionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ConsultaInformeReversiones", ReplyAction="urn:ConsultaInformeReversionesResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.ConsultaInformeReversionesResponse> ConsultaInformeReversionesAsync(CapaPresentacion.FEBata.ConsultaInformeReversionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGeneration", ReplyAction="urn:OnlineGenerationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.FEBata.OnlineGenerationResponse OnlineGeneration(CapaPresentacion.FEBata.OnlineGenerationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGeneration", ReplyAction="urn:OnlineGenerationResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineGenerationResponse> OnlineGenerationAsync(CapaPresentacion.FEBata.OnlineGenerationRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineEventos", ReplyAction="urn:OnlineEventosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.FEBata.OnlineEventosResponse OnlineEventos(CapaPresentacion.FEBata.OnlineEventosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineEventos", ReplyAction="urn:OnlineEventosResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineEventosResponse> OnlineEventosAsync(CapaPresentacion.FEBata.OnlineEventosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRec", ReplyAction="urn:OnlineRecoveryRecResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaPresentacion.FEBata.OnlineRecoveryRecResponse OnlineRecoveryRec(CapaPresentacion.FEBata.OnlineRecoveryRecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRec", ReplyAction="urn:OnlineRecoveryRecResponse")]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineRecoveryRecResponse> OnlineRecoveryRecAsync(CapaPresentacion.FEBata.OnlineRecoveryRecRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecovery", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        public int tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        public int tipoRetorno;
        
        public OnlineRecoveryRequest() {
        }
        
        public OnlineRecoveryRequest(string ruc, string login, string clave, int tipoDoc, string folio, int tipoRetorno) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.tipoDoc = tipoDoc;
            this.folio = folio;
            this.tipoRetorno = tipoRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineRecoveryResponse() {
        }
        
        public OnlineRecoveryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargaInformeBajas", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class CargaInformeBajasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docTxt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string periodo;
        
        public CargaInformeBajasRequest() {
        }
        
        public CargaInformeBajasRequest(string ruc, string login, string clave, string docTxt, string periodo) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.docTxt = docTxt;
            this.periodo = periodo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargaInformeBajasResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class CargaInformeBajasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public CargaInformeBajasResponse() {
        }
        
        public CargaInformeBajasResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineARC", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineARCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rucEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        public int tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=6)]
        public int estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string version;
        
        public OnlineARCRequest() {
        }
        
        public OnlineARCRequest(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int estado, string version) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.rucEmisor = rucEmisor;
            this.tipoDoc = tipoDoc;
            this.folio = folio;
            this.estado = estado;
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineARCResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineARCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineARCResponse() {
        }
        
        public OnlineARCResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineConsultaEstado", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineConsultaEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rucReceptor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fechaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=6)]
        public int estado;
        
        public OnlineConsultaEstadoRequest() {
        }
        
        public OnlineConsultaEstadoRequest(string ruc, string login, string clave, string rucReceptor, string fechaInicio, string fechaFin, int estado) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.rucReceptor = rucReceptor;
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineConsultaEstadoResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineConsultaEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineConsultaEstadoResponse() {
        }
        
        public OnlineConsultaEstadoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenInformeReversiones", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class GenInformeReversionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        public int tpoGen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tramaTxt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string periodo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=6)]
        public bool envioSUNAT;
        
        public GenInformeReversionesRequest() {
        }
        
        public GenInformeReversionesRequest(string ruc, string login, string clave, int tpoGen, string tramaTxt, string periodo, bool envioSUNAT) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.tpoGen = tpoGen;
            this.tramaTxt = tramaTxt;
            this.periodo = periodo;
            this.envioSUNAT = envioSUNAT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenInformeReversionesResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class GenInformeReversionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public GenInformeReversionesResponse() {
        }
        
        public GenInformeReversionesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDocInfo", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class AddDocInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        public int tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string infoAdicional;
        
        public AddDocInfoRequest() {
        }
        
        public AddDocInfoRequest(string ruc, string login, string clave, int tipoDoc, string folio, string infoAdicional) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.tipoDoc = tipoDoc;
            this.folio = folio;
            this.infoAdicional = infoAdicional;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddDocInfoResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class AddDocInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public AddDocInfoResponse() {
        }
        
        public AddDocInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAdjuntosRecibidos", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class listarAdjuntosRecibidosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rucEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        public int tipoDocumento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        public listarAdjuntosRecibidosRequest() {
        }
        
        public listarAdjuntosRecibidosRequest(string ruc, string login, string clave, string rucEmisor, int tipoDocumento, string folio) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.rucEmisor = rucEmisor;
            this.tipoDocumento = tipoDocumento;
            this.folio = folio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAdjuntosRecibidosResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class listarAdjuntosRecibidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public listarAdjuntosRecibidosResponse() {
        }
        
        public listarAdjuntosRecibidosResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecList", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fecha;
        
        public OnlineRecoveryRecListRequest() {
        }
        
        public OnlineRecoveryRecListRequest(string ruc, string login, string clave, string fecha) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecListResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineRecoveryRecListResponse() {
        }
        
        public OnlineRecoveryRecListResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InformeResBoletasDiario", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class InformeResBoletasDiarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fechaInforme;
        
        public InformeResBoletasDiarioRequest() {
        }
        
        public InformeResBoletasDiarioRequest(string ruc, string login, string clave, string fechaInforme) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.fechaInforme = fechaInforme;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InformeResBoletasDiarioResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class InformeResBoletasDiarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public InformeResBoletasDiarioResponse() {
        }
        
        public InformeResBoletasDiarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformeReversiones", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class ConsultaInformeReversionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        public int idRegistro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numTicketSunat;
        
        public ConsultaInformeReversionesRequest() {
        }
        
        public ConsultaInformeReversionesRequest(string ruc, string login, string clave, int idRegistro, string numTicketSunat) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.idRegistro = idRegistro;
            this.numTicketSunat = numTicketSunat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaInformeReversionesResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class ConsultaInformeReversionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public ConsultaInformeReversionesResponse() {
        }
        
        public ConsultaInformeReversionesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGeneration", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docTxt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        public int tipoFoliacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        public int tipoRetorno;
        
        public OnlineGenerationRequest() {
        }
        
        public OnlineGenerationRequest(string ruc, string login, string clave, string docTxt, int tipoFoliacion, int tipoRetorno) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.docTxt = docTxt;
            this.tipoFoliacion = tipoFoliacion;
            this.tipoRetorno = tipoRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineGenerationResponse() {
        }
        
        public OnlineGenerationResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineEventos", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineEventosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docTxt;
        
        public OnlineEventosRequest() {
        }
        
        public OnlineEventosRequest(string ruc, string login, string clave, string docTxt) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.docTxt = docTxt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineEventosResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineEventosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineEventosResponse() {
        }
        
        public OnlineEventosResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRec", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rucEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=4)]
        public int tipoDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string folio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=6)]
        public int tipoRetorno;
        
        public OnlineRecoveryRecRequest() {
        }
        
        public OnlineRecoveryRecRequest(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int tipoRetorno) {
            this.ruc = ruc;
            this.login = login;
            this.clave = clave;
            this.rucEmisor = rucEmisor;
            this.tipoDoc = tipoDoc;
            this.folio = folio;
            this.tipoRetorno = tipoRetorno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecResponse", WrapperNamespace="http://ws.online.asp.core.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.online.asp.core.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineRecoveryRecResponse() {
        }
        
        public OnlineRecoveryRecResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OnlinePortTypeChannel : CapaPresentacion.FEBata.OnlinePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlinePortTypeClient : System.ServiceModel.ClientBase<CapaPresentacion.FEBata.OnlinePortType>, CapaPresentacion.FEBata.OnlinePortType {
        
        public OnlinePortTypeClient() {
        }
        
        public OnlinePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlinePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlinePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlinePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.FEBata.OnlineRecoveryResponse CapaPresentacion.FEBata.OnlinePortType.OnlineRecovery(CapaPresentacion.FEBata.OnlineRecoveryRequest request) {
            return base.Channel.OnlineRecovery(request);
        }
        
        public string OnlineRecovery(string ruc, string login, string clave, int tipoDoc, string folio, int tipoRetorno) {
            CapaPresentacion.FEBata.OnlineRecoveryRequest inValue = new CapaPresentacion.FEBata.OnlineRecoveryRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.tipoRetorno = tipoRetorno;
            CapaPresentacion.FEBata.OnlineRecoveryResponse retVal = ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineRecovery(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineRecoveryResponse> CapaPresentacion.FEBata.OnlinePortType.OnlineRecoveryAsync(CapaPresentacion.FEBata.OnlineRecoveryRequest request) {
            return base.Channel.OnlineRecoveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineRecoveryResponse> OnlineRecoveryAsync(string ruc, string login, string clave, int tipoDoc, string folio, int tipoRetorno) {
            CapaPresentacion.FEBata.OnlineRecoveryRequest inValue = new CapaPresentacion.FEBata.OnlineRecoveryRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.tipoRetorno = tipoRetorno;
            return ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineRecoveryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.FEBata.CargaInformeBajasResponse CapaPresentacion.FEBata.OnlinePortType.CargaInformeBajas(CapaPresentacion.FEBata.CargaInformeBajasRequest request) {
            return base.Channel.CargaInformeBajas(request);
        }
        
        public string CargaInformeBajas(string ruc, string login, string clave, string docTxt, string periodo) {
            CapaPresentacion.FEBata.CargaInformeBajasRequest inValue = new CapaPresentacion.FEBata.CargaInformeBajasRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            inValue.periodo = periodo;
            CapaPresentacion.FEBata.CargaInformeBajasResponse retVal = ((CapaPresentacion.FEBata.OnlinePortType)(this)).CargaInformeBajas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.CargaInformeBajasResponse> CapaPresentacion.FEBata.OnlinePortType.CargaInformeBajasAsync(CapaPresentacion.FEBata.CargaInformeBajasRequest request) {
            return base.Channel.CargaInformeBajasAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.FEBata.CargaInformeBajasResponse> CargaInformeBajasAsync(string ruc, string login, string clave, string docTxt, string periodo) {
            CapaPresentacion.FEBata.CargaInformeBajasRequest inValue = new CapaPresentacion.FEBata.CargaInformeBajasRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            inValue.periodo = periodo;
            return ((CapaPresentacion.FEBata.OnlinePortType)(this)).CargaInformeBajasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.FEBata.OnlineARCResponse CapaPresentacion.FEBata.OnlinePortType.OnlineARC(CapaPresentacion.FEBata.OnlineARCRequest request) {
            return base.Channel.OnlineARC(request);
        }
        
        public string OnlineARC(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int estado, string version) {
            CapaPresentacion.FEBata.OnlineARCRequest inValue = new CapaPresentacion.FEBata.OnlineARCRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.estado = estado;
            inValue.version = version;
            CapaPresentacion.FEBata.OnlineARCResponse retVal = ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineARC(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineARCResponse> CapaPresentacion.FEBata.OnlinePortType.OnlineARCAsync(CapaPresentacion.FEBata.OnlineARCRequest request) {
            return base.Channel.OnlineARCAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineARCResponse> OnlineARCAsync(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int estado, string version) {
            CapaPresentacion.FEBata.OnlineARCRequest inValue = new CapaPresentacion.FEBata.OnlineARCRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.estado = estado;
            inValue.version = version;
            return ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineARCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.FEBata.OnlineConsultaEstadoResponse CapaPresentacion.FEBata.OnlinePortType.OnlineConsultaEstado(CapaPresentacion.FEBata.OnlineConsultaEstadoRequest request) {
            return base.Channel.OnlineConsultaEstado(request);
        }
        
        public string OnlineConsultaEstado(string ruc, string login, string clave, string rucReceptor, string fechaInicio, string fechaFin, int estado) {
            CapaPresentacion.FEBata.OnlineConsultaEstadoRequest inValue = new CapaPresentacion.FEBata.OnlineConsultaEstadoRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucReceptor = rucReceptor;
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            inValue.estado = estado;
            CapaPresentacion.FEBata.OnlineConsultaEstadoResponse retVal = ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineConsultaEstado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineConsultaEstadoResponse> CapaPresentacion.FEBata.OnlinePortType.OnlineConsultaEstadoAsync(CapaPresentacion.FEBata.OnlineConsultaEstadoRequest request) {
            return base.Channel.OnlineConsultaEstadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineConsultaEstadoResponse> OnlineConsultaEstadoAsync(string ruc, string login, string clave, string rucReceptor, string fechaInicio, string fechaFin, int estado) {
            CapaPresentacion.FEBata.OnlineConsultaEstadoRequest inValue = new CapaPresentacion.FEBata.OnlineConsultaEstadoRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucReceptor = rucReceptor;
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            inValue.estado = estado;
            return ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineConsultaEstadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.FEBata.GenInformeReversionesResponse CapaPresentacion.FEBata.OnlinePortType.GenInformeReversiones(CapaPresentacion.FEBata.GenInformeReversionesRequest request) {
            return base.Channel.GenInformeReversiones(request);
        }
        
        public string GenInformeReversiones(string ruc, string login, string clave, int tpoGen, string tramaTxt, string periodo, bool envioSUNAT) {
            CapaPresentacion.FEBata.GenInformeReversionesRequest inValue = new CapaPresentacion.FEBata.GenInformeReversionesRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tpoGen = tpoGen;
            inValue.tramaTxt = tramaTxt;
            inValue.periodo = periodo;
            inValue.envioSUNAT = envioSUNAT;
            CapaPresentacion.FEBata.GenInformeReversionesResponse retVal = ((CapaPresentacion.FEBata.OnlinePortType)(this)).GenInformeReversiones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.GenInformeReversionesResponse> CapaPresentacion.FEBata.OnlinePortType.GenInformeReversionesAsync(CapaPresentacion.FEBata.GenInformeReversionesRequest request) {
            return base.Channel.GenInformeReversionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.FEBata.GenInformeReversionesResponse> GenInformeReversionesAsync(string ruc, string login, string clave, int tpoGen, string tramaTxt, string periodo, bool envioSUNAT) {
            CapaPresentacion.FEBata.GenInformeReversionesRequest inValue = new CapaPresentacion.FEBata.GenInformeReversionesRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tpoGen = tpoGen;
            inValue.tramaTxt = tramaTxt;
            inValue.periodo = periodo;
            inValue.envioSUNAT = envioSUNAT;
            return ((CapaPresentacion.FEBata.OnlinePortType)(this)).GenInformeReversionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.FEBata.AddDocInfoResponse CapaPresentacion.FEBata.OnlinePortType.AddDocInfo(CapaPresentacion.FEBata.AddDocInfoRequest request) {
            return base.Channel.AddDocInfo(request);
        }
        
        public string AddDocInfo(string ruc, string login, string clave, int tipoDoc, string folio, string infoAdicional) {
            CapaPresentacion.FEBata.AddDocInfoRequest inValue = new CapaPresentacion.FEBata.AddDocInfoRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.infoAdicional = infoAdicional;
            CapaPresentacion.FEBata.AddDocInfoResponse retVal = ((CapaPresentacion.FEBata.OnlinePortType)(this)).AddDocInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.AddDocInfoResponse> CapaPresentacion.FEBata.OnlinePortType.AddDocInfoAsync(CapaPresentacion.FEBata.AddDocInfoRequest request) {
            return base.Channel.AddDocInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.FEBata.AddDocInfoResponse> AddDocInfoAsync(string ruc, string login, string clave, int tipoDoc, string folio, string infoAdicional) {
            CapaPresentacion.FEBata.AddDocInfoRequest inValue = new CapaPresentacion.FEBata.AddDocInfoRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.infoAdicional = infoAdicional;
            return ((CapaPresentacion.FEBata.OnlinePortType)(this)).AddDocInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.FEBata.listarAdjuntosRecibidosResponse CapaPresentacion.FEBata.OnlinePortType.listarAdjuntosRecibidos(CapaPresentacion.FEBata.listarAdjuntosRecibidosRequest request) {
            return base.Channel.listarAdjuntosRecibidos(request);
        }
        
        public string listarAdjuntosRecibidos(string ruc, string login, string clave, string rucEmisor, int tipoDocumento, string folio) {
            CapaPresentacion.FEBata.listarAdjuntosRecibidosRequest inValue = new CapaPresentacion.FEBata.listarAdjuntosRecibidosRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDocumento = tipoDocumento;
            inValue.folio = folio;
            CapaPresentacion.FEBata.listarAdjuntosRecibidosResponse retVal = ((CapaPresentacion.FEBata.OnlinePortType)(this)).listarAdjuntosRecibidos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.listarAdjuntosRecibidosResponse> CapaPresentacion.FEBata.OnlinePortType.listarAdjuntosRecibidosAsync(CapaPresentacion.FEBata.listarAdjuntosRecibidosRequest request) {
            return base.Channel.listarAdjuntosRecibidosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.FEBata.listarAdjuntosRecibidosResponse> listarAdjuntosRecibidosAsync(string ruc, string login, string clave, string rucEmisor, int tipoDocumento, string folio) {
            CapaPresentacion.FEBata.listarAdjuntosRecibidosRequest inValue = new CapaPresentacion.FEBata.listarAdjuntosRecibidosRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDocumento = tipoDocumento;
            inValue.folio = folio;
            return ((CapaPresentacion.FEBata.OnlinePortType)(this)).listarAdjuntosRecibidosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.FEBata.OnlineRecoveryRecListResponse CapaPresentacion.FEBata.OnlinePortType.OnlineRecoveryRecList(CapaPresentacion.FEBata.OnlineRecoveryRecListRequest request) {
            return base.Channel.OnlineRecoveryRecList(request);
        }
        
        public string OnlineRecoveryRecList(string ruc, string login, string clave, string fecha) {
            CapaPresentacion.FEBata.OnlineRecoveryRecListRequest inValue = new CapaPresentacion.FEBata.OnlineRecoveryRecListRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.fecha = fecha;
            CapaPresentacion.FEBata.OnlineRecoveryRecListResponse retVal = ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineRecoveryRecList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineRecoveryRecListResponse> CapaPresentacion.FEBata.OnlinePortType.OnlineRecoveryRecListAsync(CapaPresentacion.FEBata.OnlineRecoveryRecListRequest request) {
            return base.Channel.OnlineRecoveryRecListAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineRecoveryRecListResponse> OnlineRecoveryRecListAsync(string ruc, string login, string clave, string fecha) {
            CapaPresentacion.FEBata.OnlineRecoveryRecListRequest inValue = new CapaPresentacion.FEBata.OnlineRecoveryRecListRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.fecha = fecha;
            return ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineRecoveryRecListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.FEBata.InformeResBoletasDiarioResponse CapaPresentacion.FEBata.OnlinePortType.InformeResBoletasDiario(CapaPresentacion.FEBata.InformeResBoletasDiarioRequest request) {
            return base.Channel.InformeResBoletasDiario(request);
        }
        
        public string InformeResBoletasDiario(string ruc, string login, string clave, string fechaInforme) {
            CapaPresentacion.FEBata.InformeResBoletasDiarioRequest inValue = new CapaPresentacion.FEBata.InformeResBoletasDiarioRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.fechaInforme = fechaInforme;
            CapaPresentacion.FEBata.InformeResBoletasDiarioResponse retVal = ((CapaPresentacion.FEBata.OnlinePortType)(this)).InformeResBoletasDiario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.InformeResBoletasDiarioResponse> CapaPresentacion.FEBata.OnlinePortType.InformeResBoletasDiarioAsync(CapaPresentacion.FEBata.InformeResBoletasDiarioRequest request) {
            return base.Channel.InformeResBoletasDiarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.FEBata.InformeResBoletasDiarioResponse> InformeResBoletasDiarioAsync(string ruc, string login, string clave, string fechaInforme) {
            CapaPresentacion.FEBata.InformeResBoletasDiarioRequest inValue = new CapaPresentacion.FEBata.InformeResBoletasDiarioRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.fechaInforme = fechaInforme;
            return ((CapaPresentacion.FEBata.OnlinePortType)(this)).InformeResBoletasDiarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.FEBata.ConsultaInformeReversionesResponse CapaPresentacion.FEBata.OnlinePortType.ConsultaInformeReversiones(CapaPresentacion.FEBata.ConsultaInformeReversionesRequest request) {
            return base.Channel.ConsultaInformeReversiones(request);
        }
        
        public string ConsultaInformeReversiones(string ruc, string login, string clave, int idRegistro, string numTicketSunat) {
            CapaPresentacion.FEBata.ConsultaInformeReversionesRequest inValue = new CapaPresentacion.FEBata.ConsultaInformeReversionesRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.idRegistro = idRegistro;
            inValue.numTicketSunat = numTicketSunat;
            CapaPresentacion.FEBata.ConsultaInformeReversionesResponse retVal = ((CapaPresentacion.FEBata.OnlinePortType)(this)).ConsultaInformeReversiones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.ConsultaInformeReversionesResponse> CapaPresentacion.FEBata.OnlinePortType.ConsultaInformeReversionesAsync(CapaPresentacion.FEBata.ConsultaInformeReversionesRequest request) {
            return base.Channel.ConsultaInformeReversionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.FEBata.ConsultaInformeReversionesResponse> ConsultaInformeReversionesAsync(string ruc, string login, string clave, int idRegistro, string numTicketSunat) {
            CapaPresentacion.FEBata.ConsultaInformeReversionesRequest inValue = new CapaPresentacion.FEBata.ConsultaInformeReversionesRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.idRegistro = idRegistro;
            inValue.numTicketSunat = numTicketSunat;
            return ((CapaPresentacion.FEBata.OnlinePortType)(this)).ConsultaInformeReversionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.FEBata.OnlineGenerationResponse CapaPresentacion.FEBata.OnlinePortType.OnlineGeneration(CapaPresentacion.FEBata.OnlineGenerationRequest request) {
            return base.Channel.OnlineGeneration(request);
        }
        
        public string OnlineGeneration(string ruc, string login, string clave, string docTxt, int tipoFoliacion, int tipoRetorno) {
            CapaPresentacion.FEBata.OnlineGenerationRequest inValue = new CapaPresentacion.FEBata.OnlineGenerationRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            inValue.tipoFoliacion = tipoFoliacion;
            inValue.tipoRetorno = tipoRetorno;
            CapaPresentacion.FEBata.OnlineGenerationResponse retVal = ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineGeneration(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineGenerationResponse> CapaPresentacion.FEBata.OnlinePortType.OnlineGenerationAsync(CapaPresentacion.FEBata.OnlineGenerationRequest request) {
            return base.Channel.OnlineGenerationAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineGenerationResponse> OnlineGenerationAsync(string ruc, string login, string clave, string docTxt, int tipoFoliacion, int tipoRetorno) {
            CapaPresentacion.FEBata.OnlineGenerationRequest inValue = new CapaPresentacion.FEBata.OnlineGenerationRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            inValue.tipoFoliacion = tipoFoliacion;
            inValue.tipoRetorno = tipoRetorno;
            return ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineGenerationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.FEBata.OnlineEventosResponse CapaPresentacion.FEBata.OnlinePortType.OnlineEventos(CapaPresentacion.FEBata.OnlineEventosRequest request) {
            return base.Channel.OnlineEventos(request);
        }
        
        public string OnlineEventos(string ruc, string login, string clave, string docTxt) {
            CapaPresentacion.FEBata.OnlineEventosRequest inValue = new CapaPresentacion.FEBata.OnlineEventosRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            CapaPresentacion.FEBata.OnlineEventosResponse retVal = ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineEventos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineEventosResponse> CapaPresentacion.FEBata.OnlinePortType.OnlineEventosAsync(CapaPresentacion.FEBata.OnlineEventosRequest request) {
            return base.Channel.OnlineEventosAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineEventosResponse> OnlineEventosAsync(string ruc, string login, string clave, string docTxt) {
            CapaPresentacion.FEBata.OnlineEventosRequest inValue = new CapaPresentacion.FEBata.OnlineEventosRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.docTxt = docTxt;
            return ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineEventosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaPresentacion.FEBata.OnlineRecoveryRecResponse CapaPresentacion.FEBata.OnlinePortType.OnlineRecoveryRec(CapaPresentacion.FEBata.OnlineRecoveryRecRequest request) {
            return base.Channel.OnlineRecoveryRec(request);
        }
        
        public string OnlineRecoveryRec(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int tipoRetorno) {
            CapaPresentacion.FEBata.OnlineRecoveryRecRequest inValue = new CapaPresentacion.FEBata.OnlineRecoveryRecRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.tipoRetorno = tipoRetorno;
            CapaPresentacion.FEBata.OnlineRecoveryRecResponse retVal = ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineRecoveryRec(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineRecoveryRecResponse> CapaPresentacion.FEBata.OnlinePortType.OnlineRecoveryRecAsync(CapaPresentacion.FEBata.OnlineRecoveryRecRequest request) {
            return base.Channel.OnlineRecoveryRecAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaPresentacion.FEBata.OnlineRecoveryRecResponse> OnlineRecoveryRecAsync(string ruc, string login, string clave, string rucEmisor, int tipoDoc, string folio, int tipoRetorno) {
            CapaPresentacion.FEBata.OnlineRecoveryRecRequest inValue = new CapaPresentacion.FEBata.OnlineRecoveryRecRequest();
            inValue.ruc = ruc;
            inValue.login = login;
            inValue.clave = clave;
            inValue.rucEmisor = rucEmisor;
            inValue.tipoDoc = tipoDoc;
            inValue.folio = folio;
            inValue.tipoRetorno = tipoRetorno;
            return ((CapaPresentacion.FEBata.OnlinePortType)(this)).OnlineRecoveryRecAsync(inValue);
        }
    }
}
