--select * from [dbo].[foferta]

declare @fec_ini date='01-14-2019'
declare @fec_fin date='01-16-2019'

select PROM_TIEND from [dbo].[foferta] WITH(NOLOCK) WHERE (LEN(PROM_FINI)>0 AND LEN(PROM_FFIN)>0)
AND (PROM_FINI>=@fec_ini)

--DROP TABLE #TEMP

--GOTO SALIR
CREATE TABLE #TEMP(FC_SFAC VARCHAR(5),FC_NFAC VARCHAR(20),FC_FFAC DATE,FD_AUTO VARCHAR(10),COD_ENTID VARCHAR(10),FD_ARTI VARCHAR(10),ID_CALIDAD VARCHAR(5),FD_QFAC NUMERIC,
                   FD_PREF MONEY,FD_DREF MONEY,FD_TOTAL MONEY)    
INSERT INTO #TEMP(FC_SFAC,FC_NFAC,FC_FFAC,FD_AUTO,COD_ENTID,FD_ARTI,ID_CALIDAD,FD_QFAC,
                   FD_PREF,FD_DREF,FD_TOTAL)
select c.fc_sfac, c.fc_nfac, c.fc_ffac, 
d.FD_AUTO,  c.cod_entid,
d.fd_arti, d.id_calidad,
d.FD_QFAC, d.FD_PREF, d.FD_DREF, d.FD_TOTAL
from ffactc c with (nolock)
inner join ffactd d with (nolock) on c.COD_ENTID=d.COD_ENTID and c.FC_NINT=d.FD_NINT
where  (c.fc_ffac>=@fec_ini and c.fc_ffac<=@fec_fin)


--select TOP 5* from [dbo].[foferta] WITH(NOLOCK) WHERE (LEN(PROM_FINI)>0 AND LEN(PROM_FFIN)>0)

SELECT * FROM #TEMP C WITH(NOLOCK)
INNER JOIN [dbo].[foferta] D WITH(NOLOCK) ON left(D.PROM_TIEND,2)='50' AND C.COD_ENTID=D.PROM_TIEND AND C.FD_ARTI=D.PROM_ARTIC AND C.ID_CALIDAD=D.PROM_CALID
AND (LEN(PROM_FINI)>0 AND LEN(PROM_FFIN)>0) AND (C.FC_FFAC>=D.PROM_FINI AND C.FC_FFAC<=D.PROM_FFIN)

SELECT * FROM #TEMP C WITH(NOLOCK)
INNER JOIN [dbo].[foferta] D WITH(NOLOCK) ON D.PROM_TIEND='55555' AND C.COD_ENTID=D.PROM_TIEND AND C.FD_ARTI=D.PROM_ARTIC AND C.ID_CALIDAD=D.PROM_CALID
AND (LEN(PROM_FINI)>0 AND LEN(PROM_FFIN)>0) AND (C.FC_FFAC>=D.PROM_FINI AND C.FC_FFAC<=D.PROM_FFIN)

SELECT * FROM #TEMP C WITH(NOLOCK)
INNER JOIN [dbo].[foferta] D WITH(NOLOCK) ON D.PROM_TIEND='66666' AND C.COD_ENTID=D.PROM_TIEND AND C.FD_ARTI=D.PROM_ARTIC AND C.ID_CALIDAD=D.PROM_CALID
AND (LEN(PROM_FINI)>0 AND LEN(PROM_FFIN)>0) AND (C.FC_FFAC>=D.PROM_FINI AND C.FC_FFAC<=D.PROM_FFIN)

SELECT * FROM #TEMP C WITH(NOLOCK)
INNER JOIN [dbo].[foferta] D WITH(NOLOCK) ON D.PROM_TIEND='99999' AND C.COD_ENTID=D.PROM_TIEND AND C.FD_ARTI=D.PROM_ARTIC AND C.ID_CALIDAD=D.PROM_CALID
AND (LEN(PROM_FINI)>0 AND LEN(PROM_FFIN)>0) AND (C.FC_FFAC>=D.PROM_FINI AND C.FC_FFAC<=D.PROM_FFIN)

--INNER JOIN [dbo].[foferta] D2 WITH(NOLOCK) ON D2.PROM_TIEND='55555' AND C.COD_ENTID=D2.PROM_TIEND AND C.FD_ARTI=D2.PROM_ARTIC AND C.ID_CALIDAD=D2.PROM_CALID
--AND (C.FC_FFAC>=D2.PROM_FINI AND C.FC_FFAC<=D2.PROM_FFIN)
--SELECT * FROM #TEMP

DROP TABLE #TEMP

--SALIR: