//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato.comercioxpress {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cxpress.com/WSOrdenServicio/", ConfigurationName="comercioxpress.WSOrdenServicio")]
    public interface WSOrdenServicio {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación registrar no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cxpress.com/WSOrdenServicio/registrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaDato.comercioxpress.registrarResponse registrar(CapaDato.comercioxpress.registrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cxpress.com/WSOrdenServicio/registrar", ReplyAction="*")]
        System.Threading.Tasks.Task<CapaDato.comercioxpress.registrarResponse> registrarAsync(CapaDato.comercioxpress.registrarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cxpress.com/WSOrdenServicio/")]
    public partial class OrdenServicioReqParm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] nroPedidoField;
        
        private item[] listaItemsField;
        
        private double[] volumenField;
        
        private long[] tipoServicioField;
        
        private string[] horaInicioEntregaField;
        
        private string[] horaFinEntregaField;
        
        private long[] codClienteField;
        
        private long[] codCtaClienteField;
        
        private int[] cantPiezasField;
        
        private string[] codRef1Field;
        
        private string[] codRef2Field;
        
        private double[] valorProductoField;
        
        private double[] cobroAdicionalField;
        
        private long[] codTipoMonedaField;
        
        private long[] codTipoPagoField;
        
        private string[] devDoc1Field;
        
        private string[] devDoc2Field;
        
        private string[] devDoc3Field;
        
        private string[] devDoc4Field;
        
        private string[] devDoc5Field;
        
        private string[] devDoc6Field;
        
        private string[] devDoc7Field;
        
        private string[] devDoc8Field;
        
        private string[] obsDestinatariosCopiaField;
        
        private int[] tipoOrigenRecojoField;
        
        private long[] codTipoDocProveedorField;
        
        private string[] nroDocProveedorField;
        
        private long[] codPudoRecojoField;
        
        private long[] codDireccionProveedorField;
        
        private int[] indicadorGeneraRecojoField;
        
        private string[] direccRecojoField;
        
        private string[] refDireccRecojoField;
        
        private string[] codDepartRecojoField;
        
        private string[] codProvRecojoField;
        
        private string[] codDistRecojoField;
        
        private string[] latitudRecojoField;
        
        private string[] longitudRecojoField;
        
        private string[] nomDestinatarioRecojoField;
        
        private string[] apellDestinatarioRecojoField;
        
        private string[] codTipoDocDestRecojoField;
        
        private string[] nroDocDestRecojoField;
        
        private string[] telefDestinatarioRecojoField;
        
        private string[] emailDestinatarioRecojoField;
        
        private string[] horaIniRecojoField;
        
        private string[] horaFinRecojoField;
        
        private int[] tipoDestinoField;
        
        private string[] codPudoEntregaField;
        
        private string[] codReservaPudoField;
        
        private string[] direccEntregaField;
        
        private string[] refDireccEntregaField;
        
        private string[] codDepartEntregaField;
        
        private string[] codProvEntregaField;
        
        private string[] codDistEntregaField;
        
        private string[] latitudEntregaField;
        
        private string[] longitudEntregaField;
        
        private string[] nomDestEntregaField;
        
        private string[] apellDestEntregaField;
        
        private string[] codTipoDocDestEntregaField;
        
        private string[] nroDocDestEntregaField;
        
        private string[] telefDestEntregaField;
        
        private string[] emailDestEntregaField;
        
        private string[] nomDestEntrega1Field;
        
        private string[] apellDestEntrega1Field;
        
        private long[] codTipoDocDestEntrega1Field;
        
        private string[] nroDocDestEntrega1Field;
        
        private string[] telefDestEntrega1Field;
        
        private string[] emailDestEntrega1Field;
        
        private string[] nomDestEntrega2Field;
        
        private string[] apellDestEntrega2Field;
        
        private long[] codTipoDocDestEntrega2Field;
        
        private string[] nroDocDestEntrega2Field;
        
        private string[] telefDestEntrega2Field;
        
        private string[] emailDestEntrega2Field;
        
        private string[] idUsuarioField;
        
        private string[] deTerminalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nroPedido", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string[] nroPedido {
            get {
                return this.nroPedidoField;
            }
            set {
                this.nroPedidoField = value;
                this.RaisePropertyChanged("nroPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaItems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public item[] listaItems {
            get {
                return this.listaItemsField;
            }
            set {
                this.listaItemsField = value;
                this.RaisePropertyChanged("listaItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("volumen", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double[] volumen {
            get {
                return this.volumenField;
            }
            set {
                this.volumenField = value;
                this.RaisePropertyChanged("volumen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tipoServicio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long[] tipoServicio {
            get {
                return this.tipoServicioField;
            }
            set {
                this.tipoServicioField = value;
                this.RaisePropertyChanged("tipoServicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("horaInicioEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string[] horaInicioEntrega {
            get {
                return this.horaInicioEntregaField;
            }
            set {
                this.horaInicioEntregaField = value;
                this.RaisePropertyChanged("horaInicioEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("horaFinEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string[] horaFinEntrega {
            get {
                return this.horaFinEntregaField;
            }
            set {
                this.horaFinEntregaField = value;
                this.RaisePropertyChanged("horaFinEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codCliente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long[] codCliente {
            get {
                return this.codClienteField;
            }
            set {
                this.codClienteField = value;
                this.RaisePropertyChanged("codCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codCtaCliente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long[] codCtaCliente {
            get {
                return this.codCtaClienteField;
            }
            set {
                this.codCtaClienteField = value;
                this.RaisePropertyChanged("codCtaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cantPiezas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int[] cantPiezas {
            get {
                return this.cantPiezasField;
            }
            set {
                this.cantPiezasField = value;
                this.RaisePropertyChanged("cantPiezas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codRef1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string[] codRef1 {
            get {
                return this.codRef1Field;
            }
            set {
                this.codRef1Field = value;
                this.RaisePropertyChanged("codRef1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codRef2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string[] codRef2 {
            get {
                return this.codRef2Field;
            }
            set {
                this.codRef2Field = value;
                this.RaisePropertyChanged("codRef2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("valorProducto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public double[] valorProducto {
            get {
                return this.valorProductoField;
            }
            set {
                this.valorProductoField = value;
                this.RaisePropertyChanged("valorProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cobroAdicional", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public double[] cobroAdicional {
            get {
                return this.cobroAdicionalField;
            }
            set {
                this.cobroAdicionalField = value;
                this.RaisePropertyChanged("cobroAdicional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codTipoMoneda", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public long[] codTipoMoneda {
            get {
                return this.codTipoMonedaField;
            }
            set {
                this.codTipoMonedaField = value;
                this.RaisePropertyChanged("codTipoMoneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codTipoPago", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public long[] codTipoPago {
            get {
                return this.codTipoPagoField;
            }
            set {
                this.codTipoPagoField = value;
                this.RaisePropertyChanged("codTipoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("devDoc1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string[] devDoc1 {
            get {
                return this.devDoc1Field;
            }
            set {
                this.devDoc1Field = value;
                this.RaisePropertyChanged("devDoc1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("devDoc2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string[] devDoc2 {
            get {
                return this.devDoc2Field;
            }
            set {
                this.devDoc2Field = value;
                this.RaisePropertyChanged("devDoc2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("devDoc3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string[] devDoc3 {
            get {
                return this.devDoc3Field;
            }
            set {
                this.devDoc3Field = value;
                this.RaisePropertyChanged("devDoc3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("devDoc4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string[] devDoc4 {
            get {
                return this.devDoc4Field;
            }
            set {
                this.devDoc4Field = value;
                this.RaisePropertyChanged("devDoc4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("devDoc5", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string[] devDoc5 {
            get {
                return this.devDoc5Field;
            }
            set {
                this.devDoc5Field = value;
                this.RaisePropertyChanged("devDoc5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("devDoc6", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string[] devDoc6 {
            get {
                return this.devDoc6Field;
            }
            set {
                this.devDoc6Field = value;
                this.RaisePropertyChanged("devDoc6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("devDoc7", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string[] devDoc7 {
            get {
                return this.devDoc7Field;
            }
            set {
                this.devDoc7Field = value;
                this.RaisePropertyChanged("devDoc7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("devDoc8", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string[] devDoc8 {
            get {
                return this.devDoc8Field;
            }
            set {
                this.devDoc8Field = value;
                this.RaisePropertyChanged("devDoc8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("obsDestinatariosCopia", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string[] obsDestinatariosCopia {
            get {
                return this.obsDestinatariosCopiaField;
            }
            set {
                this.obsDestinatariosCopiaField = value;
                this.RaisePropertyChanged("obsDestinatariosCopia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tipoOrigenRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public int[] tipoOrigenRecojo {
            get {
                return this.tipoOrigenRecojoField;
            }
            set {
                this.tipoOrigenRecojoField = value;
                this.RaisePropertyChanged("tipoOrigenRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codTipoDocProveedor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public long[] codTipoDocProveedor {
            get {
                return this.codTipoDocProveedorField;
            }
            set {
                this.codTipoDocProveedorField = value;
                this.RaisePropertyChanged("codTipoDocProveedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nroDocProveedor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string[] nroDocProveedor {
            get {
                return this.nroDocProveedorField;
            }
            set {
                this.nroDocProveedorField = value;
                this.RaisePropertyChanged("nroDocProveedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codPudoRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public long[] codPudoRecojo {
            get {
                return this.codPudoRecojoField;
            }
            set {
                this.codPudoRecojoField = value;
                this.RaisePropertyChanged("codPudoRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codDireccionProveedor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public long[] codDireccionProveedor {
            get {
                return this.codDireccionProveedorField;
            }
            set {
                this.codDireccionProveedorField = value;
                this.RaisePropertyChanged("codDireccionProveedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("indicadorGeneraRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public int[] indicadorGeneraRecojo {
            get {
                return this.indicadorGeneraRecojoField;
            }
            set {
                this.indicadorGeneraRecojoField = value;
                this.RaisePropertyChanged("indicadorGeneraRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("direccRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string[] direccRecojo {
            get {
                return this.direccRecojoField;
            }
            set {
                this.direccRecojoField = value;
                this.RaisePropertyChanged("direccRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("refDireccRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string[] refDireccRecojo {
            get {
                return this.refDireccRecojoField;
            }
            set {
                this.refDireccRecojoField = value;
                this.RaisePropertyChanged("refDireccRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codDepartRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string[] codDepartRecojo {
            get {
                return this.codDepartRecojoField;
            }
            set {
                this.codDepartRecojoField = value;
                this.RaisePropertyChanged("codDepartRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codProvRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string[] codProvRecojo {
            get {
                return this.codProvRecojoField;
            }
            set {
                this.codProvRecojoField = value;
                this.RaisePropertyChanged("codProvRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codDistRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string[] codDistRecojo {
            get {
                return this.codDistRecojoField;
            }
            set {
                this.codDistRecojoField = value;
                this.RaisePropertyChanged("codDistRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("latitudRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string[] latitudRecojo {
            get {
                return this.latitudRecojoField;
            }
            set {
                this.latitudRecojoField = value;
                this.RaisePropertyChanged("latitudRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("longitudRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string[] longitudRecojo {
            get {
                return this.longitudRecojoField;
            }
            set {
                this.longitudRecojoField = value;
                this.RaisePropertyChanged("longitudRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nomDestinatarioRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string[] nomDestinatarioRecojo {
            get {
                return this.nomDestinatarioRecojoField;
            }
            set {
                this.nomDestinatarioRecojoField = value;
                this.RaisePropertyChanged("nomDestinatarioRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("apellDestinatarioRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string[] apellDestinatarioRecojo {
            get {
                return this.apellDestinatarioRecojoField;
            }
            set {
                this.apellDestinatarioRecojoField = value;
                this.RaisePropertyChanged("apellDestinatarioRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codTipoDocDestRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string[] codTipoDocDestRecojo {
            get {
                return this.codTipoDocDestRecojoField;
            }
            set {
                this.codTipoDocDestRecojoField = value;
                this.RaisePropertyChanged("codTipoDocDestRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nroDocDestRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string[] nroDocDestRecojo {
            get {
                return this.nroDocDestRecojoField;
            }
            set {
                this.nroDocDestRecojoField = value;
                this.RaisePropertyChanged("nroDocDestRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telefDestinatarioRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string[] telefDestinatarioRecojo {
            get {
                return this.telefDestinatarioRecojoField;
            }
            set {
                this.telefDestinatarioRecojoField = value;
                this.RaisePropertyChanged("telefDestinatarioRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("emailDestinatarioRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string[] emailDestinatarioRecojo {
            get {
                return this.emailDestinatarioRecojoField;
            }
            set {
                this.emailDestinatarioRecojoField = value;
                this.RaisePropertyChanged("emailDestinatarioRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("horaIniRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string[] horaIniRecojo {
            get {
                return this.horaIniRecojoField;
            }
            set {
                this.horaIniRecojoField = value;
                this.RaisePropertyChanged("horaIniRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("horaFinRecojo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string[] horaFinRecojo {
            get {
                return this.horaFinRecojoField;
            }
            set {
                this.horaFinRecojoField = value;
                this.RaisePropertyChanged("horaFinRecojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tipoDestino", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public int[] tipoDestino {
            get {
                return this.tipoDestinoField;
            }
            set {
                this.tipoDestinoField = value;
                this.RaisePropertyChanged("tipoDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codPudoEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string[] codPudoEntrega {
            get {
                return this.codPudoEntregaField;
            }
            set {
                this.codPudoEntregaField = value;
                this.RaisePropertyChanged("codPudoEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codReservaPudo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string[] codReservaPudo {
            get {
                return this.codReservaPudoField;
            }
            set {
                this.codReservaPudoField = value;
                this.RaisePropertyChanged("codReservaPudo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("direccEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string[] direccEntrega {
            get {
                return this.direccEntregaField;
            }
            set {
                this.direccEntregaField = value;
                this.RaisePropertyChanged("direccEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("refDireccEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string[] refDireccEntrega {
            get {
                return this.refDireccEntregaField;
            }
            set {
                this.refDireccEntregaField = value;
                this.RaisePropertyChanged("refDireccEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codDepartEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string[] codDepartEntrega {
            get {
                return this.codDepartEntregaField;
            }
            set {
                this.codDepartEntregaField = value;
                this.RaisePropertyChanged("codDepartEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codProvEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string[] codProvEntrega {
            get {
                return this.codProvEntregaField;
            }
            set {
                this.codProvEntregaField = value;
                this.RaisePropertyChanged("codProvEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codDistEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string[] codDistEntrega {
            get {
                return this.codDistEntregaField;
            }
            set {
                this.codDistEntregaField = value;
                this.RaisePropertyChanged("codDistEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("latitudEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string[] latitudEntrega {
            get {
                return this.latitudEntregaField;
            }
            set {
                this.latitudEntregaField = value;
                this.RaisePropertyChanged("latitudEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("longitudEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string[] longitudEntrega {
            get {
                return this.longitudEntregaField;
            }
            set {
                this.longitudEntregaField = value;
                this.RaisePropertyChanged("longitudEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nomDestEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string[] nomDestEntrega {
            get {
                return this.nomDestEntregaField;
            }
            set {
                this.nomDestEntregaField = value;
                this.RaisePropertyChanged("nomDestEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("apellDestEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string[] apellDestEntrega {
            get {
                return this.apellDestEntregaField;
            }
            set {
                this.apellDestEntregaField = value;
                this.RaisePropertyChanged("apellDestEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codTipoDocDestEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string[] codTipoDocDestEntrega {
            get {
                return this.codTipoDocDestEntregaField;
            }
            set {
                this.codTipoDocDestEntregaField = value;
                this.RaisePropertyChanged("codTipoDocDestEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nroDocDestEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string[] nroDocDestEntrega {
            get {
                return this.nroDocDestEntregaField;
            }
            set {
                this.nroDocDestEntregaField = value;
                this.RaisePropertyChanged("nroDocDestEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telefDestEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public string[] telefDestEntrega {
            get {
                return this.telefDestEntregaField;
            }
            set {
                this.telefDestEntregaField = value;
                this.RaisePropertyChanged("telefDestEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("emailDestEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public string[] emailDestEntrega {
            get {
                return this.emailDestEntregaField;
            }
            set {
                this.emailDestEntregaField = value;
                this.RaisePropertyChanged("emailDestEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nomDestEntrega1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public string[] nomDestEntrega1 {
            get {
                return this.nomDestEntrega1Field;
            }
            set {
                this.nomDestEntrega1Field = value;
                this.RaisePropertyChanged("nomDestEntrega1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("apellDestEntrega1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public string[] apellDestEntrega1 {
            get {
                return this.apellDestEntrega1Field;
            }
            set {
                this.apellDestEntrega1Field = value;
                this.RaisePropertyChanged("apellDestEntrega1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codTipoDocDestEntrega1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=63)]
        public long[] codTipoDocDestEntrega1 {
            get {
                return this.codTipoDocDestEntrega1Field;
            }
            set {
                this.codTipoDocDestEntrega1Field = value;
                this.RaisePropertyChanged("codTipoDocDestEntrega1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nroDocDestEntrega1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=64)]
        public string[] nroDocDestEntrega1 {
            get {
                return this.nroDocDestEntrega1Field;
            }
            set {
                this.nroDocDestEntrega1Field = value;
                this.RaisePropertyChanged("nroDocDestEntrega1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telefDestEntrega1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=65)]
        public string[] telefDestEntrega1 {
            get {
                return this.telefDestEntrega1Field;
            }
            set {
                this.telefDestEntrega1Field = value;
                this.RaisePropertyChanged("telefDestEntrega1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("emailDestEntrega1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=66)]
        public string[] emailDestEntrega1 {
            get {
                return this.emailDestEntrega1Field;
            }
            set {
                this.emailDestEntrega1Field = value;
                this.RaisePropertyChanged("emailDestEntrega1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nomDestEntrega2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=67)]
        public string[] nomDestEntrega2 {
            get {
                return this.nomDestEntrega2Field;
            }
            set {
                this.nomDestEntrega2Field = value;
                this.RaisePropertyChanged("nomDestEntrega2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("apellDestEntrega2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=68)]
        public string[] apellDestEntrega2 {
            get {
                return this.apellDestEntrega2Field;
            }
            set {
                this.apellDestEntrega2Field = value;
                this.RaisePropertyChanged("apellDestEntrega2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codTipoDocDestEntrega2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=69)]
        public long[] codTipoDocDestEntrega2 {
            get {
                return this.codTipoDocDestEntrega2Field;
            }
            set {
                this.codTipoDocDestEntrega2Field = value;
                this.RaisePropertyChanged("codTipoDocDestEntrega2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nroDocDestEntrega2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=70)]
        public string[] nroDocDestEntrega2 {
            get {
                return this.nroDocDestEntrega2Field;
            }
            set {
                this.nroDocDestEntrega2Field = value;
                this.RaisePropertyChanged("nroDocDestEntrega2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("telefDestEntrega2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=71)]
        public string[] telefDestEntrega2 {
            get {
                return this.telefDestEntrega2Field;
            }
            set {
                this.telefDestEntrega2Field = value;
                this.RaisePropertyChanged("telefDestEntrega2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("emailDestEntrega2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=72)]
        public string[] emailDestEntrega2 {
            get {
                return this.emailDestEntrega2Field;
            }
            set {
                this.emailDestEntrega2Field = value;
                this.RaisePropertyChanged("emailDestEntrega2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("idUsuario", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=73)]
        public string[] idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deTerminal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=74)]
        public string[] deTerminal {
            get {
                return this.deTerminalField;
            }
            set {
                this.deTerminalField = value;
                this.RaisePropertyChanged("deTerminal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cxpress.com/WSOrdenServicio/")]
    public partial class item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] descItemField;
        
        private int[] cantItemField;
        
        private float[] pesoMasaField;
        
        private float[] altoItemField;
        
        private float[] largoItemField;
        
        private float[] anchoItemField;
        
        private float[] valorItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("descItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string[] descItem {
            get {
                return this.descItemField;
            }
            set {
                this.descItemField = value;
                this.RaisePropertyChanged("descItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cantItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int[] cantItem {
            get {
                return this.cantItemField;
            }
            set {
                this.cantItemField = value;
                this.RaisePropertyChanged("cantItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pesoMasa", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public float[] pesoMasa {
            get {
                return this.pesoMasaField;
            }
            set {
                this.pesoMasaField = value;
                this.RaisePropertyChanged("pesoMasa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("altoItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public float[] altoItem {
            get {
                return this.altoItemField;
            }
            set {
                this.altoItemField = value;
                this.RaisePropertyChanged("altoItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("largoItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public float[] largoItem {
            get {
                return this.largoItemField;
            }
            set {
                this.largoItemField = value;
                this.RaisePropertyChanged("largoItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("anchoItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public float[] anchoItem {
            get {
                return this.anchoItemField;
            }
            set {
                this.anchoItemField = value;
                this.RaisePropertyChanged("anchoItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("valorItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public float[] valorItem {
            get {
                return this.valorItemField;
            }
            set {
                this.valorItemField = value;
                this.RaisePropertyChanged("valorItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cxpress.com/WSOrdenServicio/")]
    public partial class pieza : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nuPiezaField;
        
        private string descCortaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nuPieza {
            get {
                return this.nuPiezaField;
            }
            set {
                this.nuPiezaField = value;
                this.RaisePropertyChanged("nuPieza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descCorta {
            get {
                return this.descCortaField;
            }
            set {
                this.descCortaField = value;
                this.RaisePropertyChanged("descCorta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cxpress.com/WSOrdenServicio/")]
    public partial class response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int indicadorExitoField;
        
        private string msgField;
        
        private string nroOrdenServicioField;
        
        private pieza[] listaPiezasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int indicadorExito {
            get {
                return this.indicadorExitoField;
            }
            set {
                this.indicadorExitoField = value;
                this.RaisePropertyChanged("indicadorExito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nroOrdenServicio {
            get {
                return this.nroOrdenServicioField;
            }
            set {
                this.nroOrdenServicioField = value;
                this.RaisePropertyChanged("nroOrdenServicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaPiezas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public pieza[] listaPiezas {
            get {
                return this.listaPiezasField;
            }
            set {
                this.listaPiezasField = value;
                this.RaisePropertyChanged("listaPiezas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public CapaDato.comercioxpress.OrdenServicioReqParm entrada;
        
        public registrarRequest() {
        }
        
        public registrarRequest(CapaDato.comercioxpress.OrdenServicioReqParm entrada) {
            this.entrada = entrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public CapaDato.comercioxpress.response salida;
        
        public registrarResponse() {
        }
        
        public registrarResponse(CapaDato.comercioxpress.response salida) {
            this.salida = salida;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSOrdenServicioChannel : CapaDato.comercioxpress.WSOrdenServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSOrdenServicioClient : System.ServiceModel.ClientBase<CapaDato.comercioxpress.WSOrdenServicio>, CapaDato.comercioxpress.WSOrdenServicio {
        
        public WSOrdenServicioClient() {
        }
        
        public WSOrdenServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSOrdenServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOrdenServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOrdenServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaDato.comercioxpress.registrarResponse CapaDato.comercioxpress.WSOrdenServicio.registrar(CapaDato.comercioxpress.registrarRequest request) {
            return base.Channel.registrar(request);
        }
        
        public CapaDato.comercioxpress.response registrar(CapaDato.comercioxpress.OrdenServicioReqParm entrada) {
            CapaDato.comercioxpress.registrarRequest inValue = new CapaDato.comercioxpress.registrarRequest();
            inValue.entrada = entrada;
            CapaDato.comercioxpress.registrarResponse retVal = ((CapaDato.comercioxpress.WSOrdenServicio)(this)).registrar(inValue);
            return retVal.salida;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaDato.comercioxpress.registrarResponse> CapaDato.comercioxpress.WSOrdenServicio.registrarAsync(CapaDato.comercioxpress.registrarRequest request) {
            return base.Channel.registrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaDato.comercioxpress.registrarResponse> registrarAsync(CapaDato.comercioxpress.OrdenServicioReqParm entrada) {
            CapaDato.comercioxpress.registrarRequest inValue = new CapaDato.comercioxpress.registrarRequest();
            inValue.entrada = entrada;
            return ((CapaDato.comercioxpress.WSOrdenServicio)(this)).registrarAsync(inValue);
        }
    }
}
